// Shared KMP remote layer (Ktor, DTOs). Phase D — see docs/kmp-migration-plan.md.
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.kotlin.serialization)
}

fun escapeKotlinStringLiteral(value: String): String =
    buildString(value.length * 2) {
        for (ch in value) {
            when (ch) {
                '\\' -> append("\\\\")
                '"' -> append("\\\"")
                '\n' -> append("\\n")
                '\r' -> append("\\r")
                '\t' -> append("\\t")
                '$' -> append("\\$")
                else -> append(ch)
            }
        }
    }

val generatedSuperHeroKotlin = layout.buildDirectory.dir("generated/superhero/kotlin")

val generateSuperHeroApiToken =
    tasks.register("generateSuperHeroApiToken") {
        val raw = System.getenv("SUPER_HERO_API_TOKEN") ?: ""
        val escaped = escapeKotlinStringLiteral(raw)
        inputs.property("superHeroApiToken", raw)
        outputs.dir(generatedSuperHeroKotlin)
        doLast {
            val outDir = generatedSuperHeroKotlin.get().asFile.resolve("com/shodo/android/shared/api")
            outDir.mkdirs()
            outDir.resolve("SuperHeroApiToken.generated.kt").writeText(
                """
                package com.shodo.android.shared.api

                // Generated by Gradle task `generateSuperHeroApiToken` from SUPER_HERO_API_TOKEN at build time (all targets).
                internal const val SUPER_HERO_API_TOKEN: String = "$escaped"

                """.trimIndent(),
            )
        }
    }

kotlin {
    androidTarget {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_17)
        }
    }

    iosArm64()
    iosSimulatorArm64()

    sourceSets {
        commonMain {
            kotlin.srcDir(generatedSuperHeroKotlin)
            dependencies {
                api(project(":shared:domain"))
                implementation(libs.koin.core)
                implementation(libs.ktor.client.core)
                implementation(libs.ktor.client.content.negotiation)
                implementation(libs.ktor.serialization.kotlinx.json)
                implementation(libs.kotlinx.serialization.json)
                implementation(libs.kotlinx.coroutines.core)
            }
        }
        androidMain.dependencies {
            implementation(libs.ktor.client.okhttp)
        }
        iosMain.dependencies {
            implementation(libs.ktor.client.darwin)
        }
    }
}

android {
    namespace = "com.shodo.android.shared.api"
    compileSdk = 36

    defaultConfig {
        minSdk = 26
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

afterEvaluate {
    tasks.matching { task ->
        task.project == project &&
            task.name.contains("compile", ignoreCase = true) &&
            task.name.contains("Kotlin", ignoreCase = true)
    }.configureEach {
        dependsOn(generateSuperHeroApiToken)
    }
}
